# Name of the workflow
name: Deploy Frontend to HostGator

# This workflow runs only when you push changes to the 'public' folder on the main branch
on:
  push:
    branches:
      - main
    paths:
      - 'public/**'

jobs:
  deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: ./public_html/
