# .github/workflows/staging.yml
name: Run Checks for Staging Preview

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Notify Render of new commit
        run: |
          echo "Build successful. Render will create a preview environment for this PR."
